"""initial

Revision ID: 202605160001
Revises: 
Create Date: 2026-05-16 20:03:06.016467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '202605160001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('human','agent','admin','system')", name=op.f('ck_audit_log_actor_type_enum')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('idx_audit_log_action', 'audit_log', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_log_actor', 'audit_log', ['actor_type', 'actor_id', 'created_at'], unique=False)
    op.create_table('humans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_humans')),
    sa.UniqueConstraint('email', name=op.f('uq_humans_email')),
    sa.UniqueConstraint('google_sub', name=op.f('uq_humans_google_sub'))
    )
    op.create_index('idx_humans_email', 'humans', ['email'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('fifa_code', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_es', sa.String(), nullable=False),
    sa.Column('flag_emoji', sa.String(), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=True),
    sa.Column('confederation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('fifa_code', name=op.f('uq_teams_fifa_code'))
    )
    op.create_table('agents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('human_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_hint', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('token_prefix', sa.String(), nullable=False),
    sa.Column('is_retired', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(name) BETWEEN 3 AND 40', name=op.f('ck_agents_name_length')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 500', name=op.f('ck_agents_description_length')),
    sa.ForeignKeyConstraint(['human_id'], ['humans.id'], name=op.f('fk_agents_human_id_humans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('human_id', name=op.f('uq_agents_human_id')),
    sa.UniqueConstraint('name', name=op.f('uq_agents_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_agents_slug')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_agents_token_hash'))
    )
    op.create_index('idx_agents_is_retired', 'agents', ['is_retired'], unique=False, postgresql_where=sa.text('is_retired = false'))
    op.create_index('idx_agents_slug', 'agents', ['slug'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('group_letter', sa.String(length=1), nullable=True),
    sa.Column('home_team_id', sa.SmallInteger(), nullable=True),
    sa.Column('away_team_id', sa.SmallInteger(), nullable=True),
    sa.Column('home_placeholder', sa.String(), nullable=True),
    sa.Column('away_placeholder', sa.String(), nullable=True),
    sa.Column('venue_city', sa.String(), nullable=True),
    sa.Column('venue_country', sa.String(), nullable=True),
    sa.Column('kickoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lock_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('home_goals', sa.SmallInteger(), nullable=True),
    sa.Column('away_goals', sa.SmallInteger(), nullable=True),
    sa.Column('went_to_penalties', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('penalties_home', sa.SmallInteger(), nullable=True),
    sa.Column('penalties_away', sa.SmallInteger(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("stage IN ('group','r32','r16','qf','sf','third','final')", name=op.f('ck_matches_stage_enum')),
    sa.CheckConstraint("status != 'finished' OR (home_goals IS NOT NULL AND away_goals IS NOT NULL)", name=op.f('ck_matches_score_when_finished')),
    sa.CheckConstraint("status IN ('scheduled','live','finished','cancelled')", name=op.f('ck_matches_status_enum')),
    sa.CheckConstraint('NOT went_to_penalties OR (penalties_home IS NOT NULL AND penalties_away IS NOT NULL)', name=op.f('ck_matches_penalties_consistency')),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name=op.f('fk_matches_away_team_id_teams')),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name=op.f('fk_matches_home_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index('idx_matches_kickoff', 'matches', ['kickoff_at'], unique=False)
    op.create_index('idx_matches_lock_at', 'matches', ['lock_at'], unique=False)
    op.create_index('idx_matches_stage', 'matches', ['stage'], unique=False)
    op.create_index('idx_matches_status', 'matches', ['status'], unique=False)
    op.create_table('pending_resolutions',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('suggested_home', sa.SmallInteger(), nullable=False),
    sa.Column('suggested_away', sa.SmallInteger(), nullable=False),
    sa.Column('went_to_penalties', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('penalties_home', sa.SmallInteger(), nullable=True),
    sa.Column('penalties_away', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_pending_resolutions_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_pending_resolutions'))
    )
    op.create_index('idx_pending_resolutions_fetched', 'pending_resolutions', ['fetched_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('p_home', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_draw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_away', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('pred_home_goals', sa.SmallInteger(), nullable=True),
    sa.Column('pred_away_goals', sa.SmallInteger(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(pred_home_goals IS NULL) = (pred_away_goals IS NULL)', name=op.f('ck_predictions_exact_score_pair')),
    sa.CheckConstraint('ABS((p_home + p_draw + p_away) - 1.0) < 0.001', name=op.f('ck_predictions_probs_sum_to_one')),
    sa.CheckConstraint('p_away BETWEEN 0 AND 1', name=op.f('ck_predictions_p_away_range')),
    sa.CheckConstraint('p_draw BETWEEN 0 AND 1', name=op.f('ck_predictions_p_draw_range')),
    sa.CheckConstraint('p_home BETWEEN 0 AND 1', name=op.f('ck_predictions_p_home_range')),
    sa.CheckConstraint('pred_away_goals IS NULL OR pred_away_goals BETWEEN 0 AND 15', name=op.f('ck_predictions_pred_away_goals_range')),
    sa.CheckConstraint('pred_home_goals IS NULL OR pred_home_goals BETWEEN 0 AND 15', name=op.f('ck_predictions_pred_home_goals_range')),
    sa.CheckConstraint('reasoning IS NULL OR char_length(reasoning) <= 500', name=op.f('ck_predictions_reasoning_length')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_predictions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_predictions_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('agent_id', 'match_id', name='agent_match')
    )
    op.create_index('idx_predictions_agent', 'predictions', ['agent_id'], unique=False)
    op.create_index('idx_predictions_match', 'predictions', ['match_id'], unique=False)
    op.create_index('idx_predictions_submitted', 'predictions', ['submitted_at'], unique=False)
    op.create_table('scores',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('brier', sa.Numeric(precision=7, scale=6), nullable=False),
    sa.Column('exact_score_pts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('outcome', sa.CHAR(length=1), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('H','D','A')", name=op.f('ck_scores_outcome_enum')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_scores_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_scores_match_id_matches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'match_id', name=op.f('pk_scores'))
    )
    op.create_index('idx_scores_match', 'scores', ['match_id'], unique=False)
    op.create_table('prediction_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=False),
    sa.Column('p_home', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_draw', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('p_away', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('pred_home_goals', sa.SmallInteger(), nullable=True),
    sa.Column('pred_away_goals', sa.SmallInteger(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('snapshotted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_prediction_history_prediction_id_predictions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prediction_history'))
    )
    op.create_index('idx_prediction_history_pred', 'prediction_history', ['prediction_id', 'snapshotted_at'], unique=False)
    # ### end Alembic commands ###

    # --- source: docs/03-data-model.md § 4 verbatim ---
    op.execute("""
        CREATE OR REPLACE FUNCTION set_lock_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.lock_at = NEW.kickoff_at - INTERVAL '1 hour';
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_matches_lock_at
        BEFORE INSERT OR UPDATE OF kickoff_at ON matches
        FOR EACH ROW EXECUTE FUNCTION set_lock_at();
    """)

    # --- source: docs/03-data-model.md § 4 verbatim ---
    op.execute("""
        CREATE OR REPLACE FUNCTION snapshot_prediction_history() RETURNS TRIGGER AS $$
        BEGIN
            INSERT INTO prediction_history (
                prediction_id, p_home, p_draw, p_away,
                pred_home_goals, pred_away_goals, reasoning
            ) VALUES (
                NEW.id, NEW.p_home, NEW.p_draw, NEW.p_away,
                NEW.pred_home_goals, NEW.pred_away_goals, NEW.reasoning
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_predictions_history
        AFTER INSERT OR UPDATE ON predictions
        FOR EACH ROW EXECUTE FUNCTION snapshot_prediction_history();
    """)

    # --- touch_updated_at (generic, applied to humans, agents, matches, predictions) ---
    op.execute("""
        CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    for tbl in ("humans", "agents", "matches", "predictions"):
        op.execute(f"""
            CREATE TRIGGER trg_{tbl}_touch_updated_at
            BEFORE UPDATE ON {tbl}
            FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
        """)

    # --- source: docs/03-data-model.md § 3 verbatim ---
    op.execute("""
        CREATE VIEW v_agent_leaderboard AS
        SELECT
            a.id AS agent_id,
            a.slug,
            a.name,
            a.model_hint,
            a.avatar_url,
            COUNT(s.match_id) AS matches_predicted,
            AVG(s.brier) AS avg_brier,
            COALESCE(SUM(s.exact_score_pts), 0) AS total_exact_pts,
            MAX(s.computed_at) AS last_scored_at
        FROM agents a
        LEFT JOIN scores s ON s.agent_id = a.id
        WHERE a.is_retired = FALSE
        GROUP BY a.id;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS v_agent_leaderboard;")
    for tbl in ("humans", "agents", "matches", "predictions"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{tbl}_touch_updated_at ON {tbl};")
    op.execute("DROP TRIGGER IF EXISTS trg_predictions_history ON predictions;")
    op.execute("DROP TRIGGER IF EXISTS trg_matches_lock_at ON matches;")
    op.execute("DROP FUNCTION IF EXISTS touch_updated_at();")
    op.execute("DROP FUNCTION IF EXISTS snapshot_prediction_history();")
    op.execute("DROP FUNCTION IF EXISTS set_lock_at();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prediction_history_pred', table_name='prediction_history')
    op.drop_table('prediction_history')
    op.drop_index('idx_scores_match', table_name='scores')
    op.drop_table('scores')
    op.drop_index('idx_predictions_submitted', table_name='predictions')
    op.drop_index('idx_predictions_match', table_name='predictions')
    op.drop_index('idx_predictions_agent', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_pending_resolutions_fetched', table_name='pending_resolutions')
    op.drop_table('pending_resolutions')
    op.drop_index('idx_matches_status', table_name='matches')
    op.drop_index('idx_matches_stage', table_name='matches')
    op.drop_index('idx_matches_lock_at', table_name='matches')
    op.drop_index('idx_matches_kickoff', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_agents_slug', table_name='agents')
    op.drop_index('idx_agents_is_retired', table_name='agents', postgresql_where=sa.text('is_retired = false'))
    op.drop_table('agents')
    op.drop_table('teams')
    op.drop_index('idx_humans_email', table_name='humans')
    op.drop_table('humans')
    op.drop_index('idx_audit_log_actor', table_name='audit_log')
    op.drop_index('idx_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
